### PR TITLE
Inserting typescript declarations

### PR DESCRIPTION
**Pull request by andrelmlins**
Hello @albertodeago ,

Great project, congratulations. The curl-generator does not contains typescript declarations. To generate the statements through the rollup, I had to update the dependencies.

### CODE REVIEW

**Comment by albertodeago** [comment]
Hi @andrelmlins 
thanks for the kind words and thanks for the PR. Look's great to be honest 🥇

**Comment by andrelmlins** [comment]
@albertodeago will have new version?

**Comment by albertodeago** [comment]
@andrelmlins sorry... I will publish it in 3-4 hours, as soon as I reach my home pc

**Comment by andrelmlins** [comment]
Okay, very thank

**Comment by albertodeago** [comment]
It's out @andrelmlins

**Pull request merged**
